2024-03-28 19:12:00,874 INFO    MainThread:308147 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-03-28 19:12:00,875 INFO    MainThread:308147 [wandb_setup.py:_flush():76] Configure stats pid to 308147
2024-03-28 19:12:00,875 INFO    MainThread:308147 [wandb_setup.py:_flush():76] Loading settings from /home/research/.config/wandb/settings
2024-03-28 19:12:00,875 INFO    MainThread:308147 [wandb_setup.py:_flush():76] Loading settings from /home/research/Columbia/codemath/notebooks/wandb/settings
2024-03-28 19:12:00,875 WARNING MainThread:308147 [wandb_setup.py:_flush():76] Unknown environment variable: WANDB_LOG_MODEL
2024-03-28 19:12:00,875 WARNING MainThread:308147 [wandb_setup.py:_flush():76] Unknown environment variable: WANDB_WATCH
2024-03-28 19:12:00,875 INFO    MainThread:308147 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'codemath'}
2024-03-28 19:12:00,876 INFO    MainThread:308147 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-28 19:12:00,876 INFO    MainThread:308147 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'notebooks/finetune_on_gsm8k.py', 'program_abspath': '/home/research/Columbia/codemath/notebooks/finetune_on_gsm8k.py', 'program': '/home/research/Columbia/codemath/notebooks/finetune_on_gsm8k.py'}
2024-03-28 19:12:00,876 INFO    MainThread:308147 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-03-28 19:12:00,876 INFO    MainThread:308147 [wandb_init.py:_log_setup():527] Logging user logs to /home/research/Columbia/codemath/notebooks/wandb/run-20240328_191200-95c6nckd/logs/debug.log
2024-03-28 19:12:00,876 INFO    MainThread:308147 [wandb_init.py:_log_setup():528] Logging internal logs to /home/research/Columbia/codemath/notebooks/wandb/run-20240328_191200-95c6nckd/logs/debug-internal.log
2024-03-28 19:12:00,876 INFO    MainThread:308147 [wandb_init.py:init():567] calling init triggers
2024-03-28 19:12:00,876 INFO    MainThread:308147 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-03-28 19:12:00,876 INFO    MainThread:308147 [wandb_init.py:init():617] starting backend
2024-03-28 19:12:00,876 INFO    MainThread:308147 [wandb_init.py:init():621] setting up manager
2024-03-28 19:12:00,878 INFO    MainThread:308147 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-28 19:12:00,880 INFO    MainThread:308147 [wandb_init.py:init():629] backend started and connected
2024-03-28 19:12:00,884 INFO    MainThread:308147 [wandb_init.py:init():721] updated telemetry
2024-03-28 19:12:00,893 INFO    MainThread:308147 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-03-28 19:12:01,106 INFO    MainThread:308147 [wandb_run.py:_on_init():2344] communicating current version
2024-03-28 19:12:01,202 INFO    MainThread:308147 [wandb_run.py:_on_init():2353] got version response 
2024-03-28 19:12:01,202 INFO    MainThread:308147 [wandb_init.py:init():805] starting run threads in backend
2024-03-28 19:12:01,785 WARNING MainThread:308147 [wandb_init.py:init():1209] interrupted
Traceback (most recent call last):
  File "/home/research/.conda/envs/torch/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1187, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/research/.conda/envs/torch/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 818, in init
    run_start_result = run_start_handle.wait(timeout=30)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/research/.conda/envs/torch/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/research/.conda/envs/torch/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/research/.conda/envs/torch/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/research/.conda/envs/torch/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/research/.conda/envs/torch/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-03-28 19:12:09,934 WARNING MsgRouterThr:308147 [router.py:message_loop():77] message_loop has been closed
